// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressType3Choice.proto

// Protobuf Java Version: 3.25.3
package com.bank.core.proto.pain_008_001_10;

public final class AddressType3ChoiceOuterClass {
  private AddressType3ChoiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressType3ChoiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bank.core.proto.pain_008_001_10.AddressType3Choice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AddressType2Code Cd = 1;</code>
     * @return The enum numeric value on the wire for cd.
     */
    int getCdValue();
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AddressType2Code Cd = 1;</code>
     * @return The cd.
     */
    com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code getCd();

    /**
     * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
     * @return Whether the prtry field is set.
     */
    boolean hasPrtry();
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
     * @return The prtry.
     */
    com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30 getPrtry();
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
     */
    com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30OrBuilder getPrtryOrBuilder();
  }
  /**
   * Protobuf type {@code com.bank.core.proto.pain_008_001_10.AddressType3Choice}
   */
  public static final class AddressType3Choice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bank.core.proto.pain_008_001_10.AddressType3Choice)
      AddressType3ChoiceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddressType3Choice.newBuilder() to construct.
    private AddressType3Choice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddressType3Choice() {
      cd_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddressType3Choice();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice.class, com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice.Builder.class);
    }

    private int bitField0_;
    public static final int CD_FIELD_NUMBER = 1;
    private int cd_ = 0;
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AddressType2Code Cd = 1;</code>
     * @return The enum numeric value on the wire for cd.
     */
    @java.lang.Override public int getCdValue() {
      return cd_;
    }
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AddressType2Code Cd = 1;</code>
     * @return The cd.
     */
    @java.lang.Override public com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code getCd() {
      com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code result = com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code.forNumber(cd_);
      return result == null ? com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code.UNRECOGNIZED : result;
    }

    public static final int PRTRY_FIELD_NUMBER = 2;
    private com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30 prtry_;
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
     * @return Whether the prtry field is set.
     */
    @java.lang.Override
    public boolean hasPrtry() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
     * @return The prtry.
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30 getPrtry() {
      return prtry_ == null ? com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.getDefaultInstance() : prtry_;
    }
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30OrBuilder getPrtryOrBuilder() {
      return prtry_ == null ? com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.getDefaultInstance() : prtry_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cd_ != com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code.ADDR.getNumber()) {
        output.writeEnum(1, cd_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getPrtry());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cd_ != com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code.ADDR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cd_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPrtry());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice)) {
        return super.equals(obj);
      }
      com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice other = (com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice) obj;

      if (cd_ != other.cd_) return false;
      if (hasPrtry() != other.hasPrtry()) return false;
      if (hasPrtry()) {
        if (!getPrtry()
            .equals(other.getPrtry())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CD_FIELD_NUMBER;
      hash = (53 * hash) + cd_;
      if (hasPrtry()) {
        hash = (37 * hash) + PRTRY_FIELD_NUMBER;
        hash = (53 * hash) + getPrtry().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bank.core.proto.pain_008_001_10.AddressType3Choice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bank.core.proto.pain_008_001_10.AddressType3Choice)
        com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3ChoiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice.class, com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice.Builder.class);
      }

      // Construct using com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPrtryFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cd_ = 0;
        prtry_ = null;
        if (prtryBuilder_ != null) {
          prtryBuilder_.dispose();
          prtryBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_descriptor;
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice getDefaultInstanceForType() {
        return com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice.getDefaultInstance();
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice build() {
        com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice buildPartial() {
        com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice result = new com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cd_ = cd_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.prtry_ = prtryBuilder_ == null
              ? prtry_
              : prtryBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice) {
          return mergeFrom((com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice other) {
        if (other == com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice.getDefaultInstance()) return this;
        if (other.cd_ != 0) {
          setCdValue(other.getCdValue());
        }
        if (other.hasPrtry()) {
          mergePrtry(other.getPrtry());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cd_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getPrtryFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cd_ = 0;
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AddressType2Code Cd = 1;</code>
       * @return The enum numeric value on the wire for cd.
       */
      @java.lang.Override public int getCdValue() {
        return cd_;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AddressType2Code Cd = 1;</code>
       * @param value The enum numeric value on the wire for cd to set.
       * @return This builder for chaining.
       */
      public Builder setCdValue(int value) {
        cd_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AddressType2Code Cd = 1;</code>
       * @return The cd.
       */
      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code getCd() {
        com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code result = com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code.forNumber(cd_);
        return result == null ? com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AddressType2Code Cd = 1;</code>
       * @param value The cd to set.
       * @return This builder for chaining.
       */
      public Builder setCd(com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.AddressType2Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        cd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AddressType2Code Cd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cd_ = 0;
        onChanged();
        return this;
      }

      private com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30 prtry_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30, com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.Builder, com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30OrBuilder> prtryBuilder_;
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
       * @return Whether the prtry field is set.
       */
      public boolean hasPrtry() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
       * @return The prtry.
       */
      public com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30 getPrtry() {
        if (prtryBuilder_ == null) {
          return prtry_ == null ? com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.getDefaultInstance() : prtry_;
        } else {
          return prtryBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
       */
      public Builder setPrtry(com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30 value) {
        if (prtryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          prtry_ = value;
        } else {
          prtryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
       */
      public Builder setPrtry(
          com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.Builder builderForValue) {
        if (prtryBuilder_ == null) {
          prtry_ = builderForValue.build();
        } else {
          prtryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
       */
      public Builder mergePrtry(com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30 value) {
        if (prtryBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            prtry_ != null &&
            prtry_ != com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.getDefaultInstance()) {
            getPrtryBuilder().mergeFrom(value);
          } else {
            prtry_ = value;
          }
        } else {
          prtryBuilder_.mergeFrom(value);
        }
        if (prtry_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
       */
      public Builder clearPrtry() {
        bitField0_ = (bitField0_ & ~0x00000002);
        prtry_ = null;
        if (prtryBuilder_ != null) {
          prtryBuilder_.dispose();
          prtryBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
       */
      public com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.Builder getPrtryBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPrtryFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
       */
      public com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30OrBuilder getPrtryOrBuilder() {
        if (prtryBuilder_ != null) {
          return prtryBuilder_.getMessageOrBuilder();
        } else {
          return prtry_ == null ?
              com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.getDefaultInstance() : prtry_;
        }
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.GenericIdentification30 Prtry = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30, com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.Builder, com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30OrBuilder> 
          getPrtryFieldBuilder() {
        if (prtryBuilder_ == null) {
          prtryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30, com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30.Builder, com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.GenericIdentification30OrBuilder>(
                  getPrtry(),
                  getParentForChildren(),
                  isClean());
          prtry_ = null;
        }
        return prtryBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bank.core.proto.pain_008_001_10.AddressType3Choice)
    }

    // @@protoc_insertion_point(class_scope:com.bank.core.proto.pain_008_001_10.AddressType3Choice)
    private static final com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice();
    }

    public static com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddressType3Choice>
        PARSER = new com.google.protobuf.AbstractParser<AddressType3Choice>() {
      @java.lang.Override
      public AddressType3Choice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AddressType3Choice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddressType3Choice> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.AddressType3ChoiceOuterClass.AddressType3Choice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030AddressType3Choice.proto\022#com.bank.cor" +
      "e.proto.pain_008_001_10\032\026AddressType2Cod" +
      "e.proto\032\035GenericIdentification30.proto\"\244" +
      "\001\n\022AddressType3Choice\022A\n\002Cd\030\001 \001(\01625.com." +
      "bank.core.proto.pain_008_001_10.AddressT" +
      "ype2Code\022K\n\005Prtry\030\002 \001(\0132<.com.bank.core." +
      "proto.pain_008_001_10.GenericIdentificat" +
      "ion30b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.getDescriptor(),
          com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.getDescriptor(),
        });
    internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bank_core_proto_pain_008_001_10_AddressType3Choice_descriptor,
        new java.lang.String[] { "Cd", "Prtry", });
    com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.getDescriptor();
    com.bank.core.proto.pain_008_001_10.GenericIdentification30OuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
