// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/AddressType2Code.proto

// Protobuf Java Version: 3.25.3
package com.bank.core.proto.pain_008_001_10;

public final class AddressType2CodeOuterClass {
  private AddressType2CodeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.bank.core.proto.pain_008_001_10.AddressType2Code}
   */
  public enum AddressType2Code
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADDR = 0;</code>
     */
    ADDR(0),
    /**
     * <code>PBOX = 1;</code>
     */
    PBOX(1),
    /**
     * <code>HOME = 2;</code>
     */
    HOME(2),
    /**
     * <code>BIZZ = 3;</code>
     */
    BIZZ(3),
    /**
     * <code>MLTO = 4;</code>
     */
    MLTO(4),
    /**
     * <code>DLVY = 5;</code>
     */
    DLVY(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ADDR = 0;</code>
     */
    public static final int ADDR_VALUE = 0;
    /**
     * <code>PBOX = 1;</code>
     */
    public static final int PBOX_VALUE = 1;
    /**
     * <code>HOME = 2;</code>
     */
    public static final int HOME_VALUE = 2;
    /**
     * <code>BIZZ = 3;</code>
     */
    public static final int BIZZ_VALUE = 3;
    /**
     * <code>MLTO = 4;</code>
     */
    public static final int MLTO_VALUE = 4;
    /**
     * <code>DLVY = 5;</code>
     */
    public static final int DLVY_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AddressType2Code valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AddressType2Code forNumber(int value) {
      switch (value) {
        case 0: return ADDR;
        case 1: return PBOX;
        case 2: return HOME;
        case 3: return BIZZ;
        case 4: return MLTO;
        case 5: return DLVY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AddressType2Code>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AddressType2Code> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AddressType2Code>() {
            public AddressType2Code findValueByNumber(int number) {
              return AddressType2Code.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bank.core.proto.pain_008_001_10.AddressType2CodeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final AddressType2Code[] VALUES = values();

    public static AddressType2Code valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AddressType2Code(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.bank.core.proto.pain_008_001_10.AddressType2Code)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034proto/AddressType2Code.proto\022#com.bank" +
      ".core.proto.pain_008_001_10*N\n\020AddressTy" +
      "pe2Code\022\010\n\004ADDR\020\000\022\010\n\004PBOX\020\001\022\010\n\004HOME\020\002\022\010\n" +
      "\004BIZZ\020\003\022\010\n\004MLTO\020\004\022\010\n\004DLVY\020\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
