// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/AdviceType1.proto

// Protobuf Java Version: 3.25.3
package com.bank.core.proto.pain_008_001_10;

public final class AdviceType1OuterClass {
  private AdviceType1OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdviceType1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bank.core.proto.pain_008_001_10.AdviceType1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
     * @return Whether the cdtAdvc field is set.
     */
    boolean hasCdtAdvc();
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
     * @return The cdtAdvc.
     */
    com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice getCdtAdvc();
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
     */
    com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder getCdtAdvcOrBuilder();

    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
     * @return Whether the dbtAdvc field is set.
     */
    boolean hasDbtAdvc();
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
     * @return The dbtAdvc.
     */
    com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice getDbtAdvc();
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
     */
    com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder getDbtAdvcOrBuilder();
  }
  /**
   * Protobuf type {@code com.bank.core.proto.pain_008_001_10.AdviceType1}
   */
  public static final class AdviceType1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bank.core.proto.pain_008_001_10.AdviceType1)
      AdviceType1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdviceType1.newBuilder() to construct.
    private AdviceType1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdviceType1() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AdviceType1();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1.class, com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1.Builder.class);
    }

    private int bitField0_;
    public static final int CDTADVC_FIELD_NUMBER = 1;
    private com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice cdtAdvc_;
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
     * @return Whether the cdtAdvc field is set.
     */
    @java.lang.Override
    public boolean hasCdtAdvc() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
     * @return The cdtAdvc.
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice getCdtAdvc() {
      return cdtAdvc_ == null ? com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance() : cdtAdvc_;
    }
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder getCdtAdvcOrBuilder() {
      return cdtAdvc_ == null ? com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance() : cdtAdvc_;
    }

    public static final int DBTADVC_FIELD_NUMBER = 2;
    private com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice dbtAdvc_;
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
     * @return Whether the dbtAdvc field is set.
     */
    @java.lang.Override
    public boolean hasDbtAdvc() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
     * @return The dbtAdvc.
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice getDbtAdvc() {
      return dbtAdvc_ == null ? com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance() : dbtAdvc_;
    }
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder getDbtAdvcOrBuilder() {
      return dbtAdvc_ == null ? com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance() : dbtAdvc_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getCdtAdvc());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getDbtAdvc());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCdtAdvc());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDbtAdvc());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1)) {
        return super.equals(obj);
      }
      com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 other = (com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1) obj;

      if (hasCdtAdvc() != other.hasCdtAdvc()) return false;
      if (hasCdtAdvc()) {
        if (!getCdtAdvc()
            .equals(other.getCdtAdvc())) return false;
      }
      if (hasDbtAdvc() != other.hasDbtAdvc()) return false;
      if (hasDbtAdvc()) {
        if (!getDbtAdvc()
            .equals(other.getDbtAdvc())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCdtAdvc()) {
        hash = (37 * hash) + CDTADVC_FIELD_NUMBER;
        hash = (53 * hash) + getCdtAdvc().hashCode();
      }
      if (hasDbtAdvc()) {
        hash = (37 * hash) + DBTADVC_FIELD_NUMBER;
        hash = (53 * hash) + getDbtAdvc().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bank.core.proto.pain_008_001_10.AdviceType1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bank.core.proto.pain_008_001_10.AdviceType1)
        com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1.class, com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1.Builder.class);
      }

      // Construct using com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCdtAdvcFieldBuilder();
          getDbtAdvcFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cdtAdvc_ = null;
        if (cdtAdvcBuilder_ != null) {
          cdtAdvcBuilder_.dispose();
          cdtAdvcBuilder_ = null;
        }
        dbtAdvc_ = null;
        if (dbtAdvcBuilder_ != null) {
          dbtAdvcBuilder_.dispose();
          dbtAdvcBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_descriptor;
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 getDefaultInstanceForType() {
        return com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1.getDefaultInstance();
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 build() {
        com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 buildPartial() {
        com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 result = new com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cdtAdvc_ = cdtAdvcBuilder_ == null
              ? cdtAdvc_
              : cdtAdvcBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dbtAdvc_ = dbtAdvcBuilder_ == null
              ? dbtAdvc_
              : dbtAdvcBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1) {
          return mergeFrom((com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 other) {
        if (other == com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1.getDefaultInstance()) return this;
        if (other.hasCdtAdvc()) {
          mergeCdtAdvc(other.getCdtAdvc());
        }
        if (other.hasDbtAdvc()) {
          mergeDbtAdvc(other.getDbtAdvc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getCdtAdvcFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getDbtAdvcFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice cdtAdvc_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder> cdtAdvcBuilder_;
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
       * @return Whether the cdtAdvc field is set.
       */
      public boolean hasCdtAdvc() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
       * @return The cdtAdvc.
       */
      public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice getCdtAdvc() {
        if (cdtAdvcBuilder_ == null) {
          return cdtAdvc_ == null ? com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance() : cdtAdvc_;
        } else {
          return cdtAdvcBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
       */
      public Builder setCdtAdvc(com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice value) {
        if (cdtAdvcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cdtAdvc_ = value;
        } else {
          cdtAdvcBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
       */
      public Builder setCdtAdvc(
          com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder builderForValue) {
        if (cdtAdvcBuilder_ == null) {
          cdtAdvc_ = builderForValue.build();
        } else {
          cdtAdvcBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
       */
      public Builder mergeCdtAdvc(com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice value) {
        if (cdtAdvcBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            cdtAdvc_ != null &&
            cdtAdvc_ != com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance()) {
            getCdtAdvcBuilder().mergeFrom(value);
          } else {
            cdtAdvc_ = value;
          }
        } else {
          cdtAdvcBuilder_.mergeFrom(value);
        }
        if (cdtAdvc_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
       */
      public Builder clearCdtAdvc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cdtAdvc_ = null;
        if (cdtAdvcBuilder_ != null) {
          cdtAdvcBuilder_.dispose();
          cdtAdvcBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
       */
      public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder getCdtAdvcBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCdtAdvcFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
       */
      public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder getCdtAdvcOrBuilder() {
        if (cdtAdvcBuilder_ != null) {
          return cdtAdvcBuilder_.getMessageOrBuilder();
        } else {
          return cdtAdvc_ == null ?
              com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance() : cdtAdvc_;
        }
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice CdtAdvc = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder> 
          getCdtAdvcFieldBuilder() {
        if (cdtAdvcBuilder_ == null) {
          cdtAdvcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder>(
                  getCdtAdvc(),
                  getParentForChildren(),
                  isClean());
          cdtAdvc_ = null;
        }
        return cdtAdvcBuilder_;
      }

      private com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice dbtAdvc_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder> dbtAdvcBuilder_;
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
       * @return Whether the dbtAdvc field is set.
       */
      public boolean hasDbtAdvc() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
       * @return The dbtAdvc.
       */
      public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice getDbtAdvc() {
        if (dbtAdvcBuilder_ == null) {
          return dbtAdvc_ == null ? com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance() : dbtAdvc_;
        } else {
          return dbtAdvcBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
       */
      public Builder setDbtAdvc(com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice value) {
        if (dbtAdvcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dbtAdvc_ = value;
        } else {
          dbtAdvcBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
       */
      public Builder setDbtAdvc(
          com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder builderForValue) {
        if (dbtAdvcBuilder_ == null) {
          dbtAdvc_ = builderForValue.build();
        } else {
          dbtAdvcBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
       */
      public Builder mergeDbtAdvc(com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice value) {
        if (dbtAdvcBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            dbtAdvc_ != null &&
            dbtAdvc_ != com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance()) {
            getDbtAdvcBuilder().mergeFrom(value);
          } else {
            dbtAdvc_ = value;
          }
        } else {
          dbtAdvcBuilder_.mergeFrom(value);
        }
        if (dbtAdvc_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
       */
      public Builder clearDbtAdvc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dbtAdvc_ = null;
        if (dbtAdvcBuilder_ != null) {
          dbtAdvcBuilder_.dispose();
          dbtAdvcBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
       */
      public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder getDbtAdvcBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDbtAdvcFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
       */
      public com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder getDbtAdvcOrBuilder() {
        if (dbtAdvcBuilder_ != null) {
          return dbtAdvcBuilder_.getMessageOrBuilder();
        } else {
          return dbtAdvc_ == null ?
              com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.getDefaultInstance() : dbtAdvc_;
        }
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.AdviceType1Choice DbtAdvc = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder> 
          getDbtAdvcFieldBuilder() {
        if (dbtAdvcBuilder_ == null) {
          dbtAdvcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1Choice.Builder, com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.AdviceType1ChoiceOrBuilder>(
                  getDbtAdvc(),
                  getParentForChildren(),
                  isClean());
          dbtAdvc_ = null;
        }
        return dbtAdvcBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bank.core.proto.pain_008_001_10.AdviceType1)
    }

    // @@protoc_insertion_point(class_scope:com.bank.core.proto.pain_008_001_10.AdviceType1)
    private static final com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1();
    }

    public static com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdviceType1>
        PARSER = new com.google.protobuf.AbstractParser<AdviceType1>() {
      @java.lang.Override
      public AdviceType1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AdviceType1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdviceType1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.AdviceType1OuterClass.AdviceType1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/AdviceType1.proto\022#com.bank.core" +
      ".proto.pain_008_001_10\032\035proto/AdviceType" +
      "1Choice.proto\"\237\001\n\013AdviceType1\022G\n\007CdtAdvc" +
      "\030\001 \001(\01326.com.bank.core.proto.pain_008_00" +
      "1_10.AdviceType1Choice\022G\n\007DbtAdvc\030\002 \001(\0132" +
      "6.com.bank.core.proto.pain_008_001_10.Ad" +
      "viceType1Choiceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.getDescriptor(),
        });
    internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bank_core_proto_pain_008_001_10_AdviceType1_descriptor,
        new java.lang.String[] { "CdtAdvc", "DbtAdvc", });
    com.bank.core.proto.pain_008_001_10.AdviceType1ChoiceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
