// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ChargeBearerType1Code.proto

// Protobuf Java Version: 3.25.3
package com.bank.core.proto.pain_008_001_10;

public final class ChargeBearerType1CodeOuterClass {
  private ChargeBearerType1CodeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.bank.core.proto.pain_008_001_10.ChargeBearerType1Code}
   */
  public enum ChargeBearerType1Code
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ChargeBearerType1Code_CRED = 0;</code>
     */
    ChargeBearerType1Code_CRED(0),
    /**
     * <code>ChargeBearerType1Code_DEBT = 1;</code>
     */
    ChargeBearerType1Code_DEBT(1),
    /**
     * <code>ChargeBearerType1Code_SHAR = 2;</code>
     */
    ChargeBearerType1Code_SHAR(2),
    /**
     * <code>ChargeBearerType1Code_SLEV = 3;</code>
     */
    ChargeBearerType1Code_SLEV(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ChargeBearerType1Code_CRED = 0;</code>
     */
    public static final int ChargeBearerType1Code_CRED_VALUE = 0;
    /**
     * <code>ChargeBearerType1Code_DEBT = 1;</code>
     */
    public static final int ChargeBearerType1Code_DEBT_VALUE = 1;
    /**
     * <code>ChargeBearerType1Code_SHAR = 2;</code>
     */
    public static final int ChargeBearerType1Code_SHAR_VALUE = 2;
    /**
     * <code>ChargeBearerType1Code_SLEV = 3;</code>
     */
    public static final int ChargeBearerType1Code_SLEV_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChargeBearerType1Code valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ChargeBearerType1Code forNumber(int value) {
      switch (value) {
        case 0: return ChargeBearerType1Code_CRED;
        case 1: return ChargeBearerType1Code_DEBT;
        case 2: return ChargeBearerType1Code_SHAR;
        case 3: return ChargeBearerType1Code_SLEV;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChargeBearerType1Code>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChargeBearerType1Code> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChargeBearerType1Code>() {
            public ChargeBearerType1Code findValueByNumber(int number) {
              return ChargeBearerType1Code.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bank.core.proto.pain_008_001_10.ChargeBearerType1CodeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ChargeBearerType1Code[] VALUES = values();

    public static ChargeBearerType1Code valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChargeBearerType1Code(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.bank.core.proto.pain_008_001_10.ChargeBearerType1Code)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!proto/ChargeBearerType1Code.proto\022#com" +
      ".bank.core.proto.pain_008_001_10*\227\001\n\025Cha" +
      "rgeBearerType1Code\022\036\n\032ChargeBearerType1C" +
      "ode_CRED\020\000\022\036\n\032ChargeBearerType1Code_DEBT" +
      "\020\001\022\036\n\032ChargeBearerType1Code_SHAR\020\002\022\036\n\032Ch" +
      "argeBearerType1Code_SLEV\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
