// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Contact4.proto

// Protobuf Java Version: 3.25.3
package com.bank.core.proto.pain_008_001_10;

public final class Contact4OuterClass {
  private Contact4OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Contact4OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bank.core.proto.pain_008_001_10.Contact4)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bank.core.proto.pain_008_001_10.NamePrefix2Code NmPrfx = 1;</code>
     * @return The enum numeric value on the wire for nmPrfx.
     */
    int getNmPrfxValue();
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.NamePrefix2Code NmPrfx = 1;</code>
     * @return The nmPrfx.
     */
    com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code getNmPrfx();

    /**
     * <code>string Nm = 2;</code>
     * @return The nm.
     */
    java.lang.String getNm();
    /**
     * <code>string Nm = 2;</code>
     * @return The bytes for nm.
     */
    com.google.protobuf.ByteString
        getNmBytes();

    /**
     * <code>string PhneNb = 3;</code>
     * @return The phneNb.
     */
    java.lang.String getPhneNb();
    /**
     * <code>string PhneNb = 3;</code>
     * @return The bytes for phneNb.
     */
    com.google.protobuf.ByteString
        getPhneNbBytes();

    /**
     * <code>string MobNb = 4;</code>
     * @return The mobNb.
     */
    java.lang.String getMobNb();
    /**
     * <code>string MobNb = 4;</code>
     * @return The bytes for mobNb.
     */
    com.google.protobuf.ByteString
        getMobNbBytes();

    /**
     * <code>string FaxNb = 5;</code>
     * @return The faxNb.
     */
    java.lang.String getFaxNb();
    /**
     * <code>string FaxNb = 5;</code>
     * @return The bytes for faxNb.
     */
    com.google.protobuf.ByteString
        getFaxNbBytes();

    /**
     * <code>string EmailAdr = 6;</code>
     * @return The emailAdr.
     */
    java.lang.String getEmailAdr();
    /**
     * <code>string EmailAdr = 6;</code>
     * @return The bytes for emailAdr.
     */
    com.google.protobuf.ByteString
        getEmailAdrBytes();

    /**
     * <code>string EmailPurp = 7;</code>
     * @return The emailPurp.
     */
    java.lang.String getEmailPurp();
    /**
     * <code>string EmailPurp = 7;</code>
     * @return The bytes for emailPurp.
     */
    com.google.protobuf.ByteString
        getEmailPurpBytes();

    /**
     * <code>string JobTitl = 8;</code>
     * @return The jobTitl.
     */
    java.lang.String getJobTitl();
    /**
     * <code>string JobTitl = 8;</code>
     * @return The bytes for jobTitl.
     */
    com.google.protobuf.ByteString
        getJobTitlBytes();

    /**
     * <code>string Rspnsblty = 9;</code>
     * @return The rspnsblty.
     */
    java.lang.String getRspnsblty();
    /**
     * <code>string Rspnsblty = 9;</code>
     * @return The bytes for rspnsblty.
     */
    com.google.protobuf.ByteString
        getRspnsbltyBytes();

    /**
     * <code>string Dept = 10;</code>
     * @return The dept.
     */
    java.lang.String getDept();
    /**
     * <code>string Dept = 10;</code>
     * @return The bytes for dept.
     */
    com.google.protobuf.ByteString
        getDeptBytes();

    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    java.util.List<com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1> 
        getOthrList();
    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1 getOthr(int index);
    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    int getOthrCount();
    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    java.util.List<? extends com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1OrBuilder> 
        getOthrOrBuilderList();
    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1OrBuilder getOthrOrBuilder(
        int index);

    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
     * @return Whether the prefrdMtd field is set.
     */
    boolean hasPrefrdMtd();
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
     * @return The enum numeric value on the wire for prefrdMtd.
     */
    int getPrefrdMtdValue();
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
     * @return The prefrdMtd.
     */
    com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code getPrefrdMtd();
  }
  /**
   * Protobuf type {@code com.bank.core.proto.pain_008_001_10.Contact4}
   */
  public static final class Contact4 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bank.core.proto.pain_008_001_10.Contact4)
      Contact4OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Contact4.newBuilder() to construct.
    private Contact4(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Contact4() {
      nmPrfx_ = 0;
      nm_ = "";
      phneNb_ = "";
      mobNb_ = "";
      faxNb_ = "";
      emailAdr_ = "";
      emailPurp_ = "";
      jobTitl_ = "";
      rspnsblty_ = "";
      dept_ = "";
      othr_ = java.util.Collections.emptyList();
      prefrdMtd_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Contact4();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bank.core.proto.pain_008_001_10.Contact4OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_Contact4_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bank.core.proto.pain_008_001_10.Contact4OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_Contact4_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.class, com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.Builder.class);
    }

    private int bitField0_;
    public static final int NMPRFX_FIELD_NUMBER = 1;
    private int nmPrfx_ = 0;
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.NamePrefix2Code NmPrfx = 1;</code>
     * @return The enum numeric value on the wire for nmPrfx.
     */
    @java.lang.Override public int getNmPrfxValue() {
      return nmPrfx_;
    }
    /**
     * <code>.com.bank.core.proto.pain_008_001_10.NamePrefix2Code NmPrfx = 1;</code>
     * @return The nmPrfx.
     */
    @java.lang.Override public com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code getNmPrfx() {
      com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code result = com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code.forNumber(nmPrfx_);
      return result == null ? com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code.UNRECOGNIZED : result;
    }

    public static final int NM_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nm_ = "";
    /**
     * <code>string Nm = 2;</code>
     * @return The nm.
     */
    @java.lang.Override
    public java.lang.String getNm() {
      java.lang.Object ref = nm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nm_ = s;
        return s;
      }
    }
    /**
     * <code>string Nm = 2;</code>
     * @return The bytes for nm.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNmBytes() {
      java.lang.Object ref = nm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHNENB_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object phneNb_ = "";
    /**
     * <code>string PhneNb = 3;</code>
     * @return The phneNb.
     */
    @java.lang.Override
    public java.lang.String getPhneNb() {
      java.lang.Object ref = phneNb_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phneNb_ = s;
        return s;
      }
    }
    /**
     * <code>string PhneNb = 3;</code>
     * @return The bytes for phneNb.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhneNbBytes() {
      java.lang.Object ref = phneNb_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phneNb_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBNB_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mobNb_ = "";
    /**
     * <code>string MobNb = 4;</code>
     * @return The mobNb.
     */
    @java.lang.Override
    public java.lang.String getMobNb() {
      java.lang.Object ref = mobNb_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobNb_ = s;
        return s;
      }
    }
    /**
     * <code>string MobNb = 4;</code>
     * @return The bytes for mobNb.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMobNbBytes() {
      java.lang.Object ref = mobNb_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobNb_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAXNB_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object faxNb_ = "";
    /**
     * <code>string FaxNb = 5;</code>
     * @return The faxNb.
     */
    @java.lang.Override
    public java.lang.String getFaxNb() {
      java.lang.Object ref = faxNb_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        faxNb_ = s;
        return s;
      }
    }
    /**
     * <code>string FaxNb = 5;</code>
     * @return The bytes for faxNb.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFaxNbBytes() {
      java.lang.Object ref = faxNb_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faxNb_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAILADR_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object emailAdr_ = "";
    /**
     * <code>string EmailAdr = 6;</code>
     * @return The emailAdr.
     */
    @java.lang.Override
    public java.lang.String getEmailAdr() {
      java.lang.Object ref = emailAdr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emailAdr_ = s;
        return s;
      }
    }
    /**
     * <code>string EmailAdr = 6;</code>
     * @return The bytes for emailAdr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailAdrBytes() {
      java.lang.Object ref = emailAdr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emailAdr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAILPURP_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object emailPurp_ = "";
    /**
     * <code>string EmailPurp = 7;</code>
     * @return The emailPurp.
     */
    @java.lang.Override
    public java.lang.String getEmailPurp() {
      java.lang.Object ref = emailPurp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emailPurp_ = s;
        return s;
      }
    }
    /**
     * <code>string EmailPurp = 7;</code>
     * @return The bytes for emailPurp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailPurpBytes() {
      java.lang.Object ref = emailPurp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emailPurp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOBTITL_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object jobTitl_ = "";
    /**
     * <code>string JobTitl = 8;</code>
     * @return The jobTitl.
     */
    @java.lang.Override
    public java.lang.String getJobTitl() {
      java.lang.Object ref = jobTitl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobTitl_ = s;
        return s;
      }
    }
    /**
     * <code>string JobTitl = 8;</code>
     * @return The bytes for jobTitl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJobTitlBytes() {
      java.lang.Object ref = jobTitl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobTitl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RSPNSBLTY_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rspnsblty_ = "";
    /**
     * <code>string Rspnsblty = 9;</code>
     * @return The rspnsblty.
     */
    @java.lang.Override
    public java.lang.String getRspnsblty() {
      java.lang.Object ref = rspnsblty_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rspnsblty_ = s;
        return s;
      }
    }
    /**
     * <code>string Rspnsblty = 9;</code>
     * @return The bytes for rspnsblty.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRspnsbltyBytes() {
      java.lang.Object ref = rspnsblty_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rspnsblty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPT_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dept_ = "";
    /**
     * <code>string Dept = 10;</code>
     * @return The dept.
     */
    @java.lang.Override
    public java.lang.String getDept() {
      java.lang.Object ref = dept_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dept_ = s;
        return s;
      }
    }
    /**
     * <code>string Dept = 10;</code>
     * @return The bytes for dept.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeptBytes() {
      java.lang.Object ref = dept_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dept_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OTHR_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private java.util.List<com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1> othr_;
    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    @java.lang.Override
    public java.util.List<com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1> getOthrList() {
      return othr_;
    }
    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1OrBuilder> 
        getOthrOrBuilderList() {
      return othr_;
    }
    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    @java.lang.Override
    public int getOthrCount() {
      return othr_.size();
    }
    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1 getOthr(int index) {
      return othr_.get(index);
    }
    /**
     * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1OrBuilder getOthrOrBuilder(
        int index) {
      return othr_.get(index);
    }

    public static final int PREFRDMTD_FIELD_NUMBER = 12;
    private int prefrdMtd_ = 0;
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
     * @return Whether the prefrdMtd field is set.
     */
    @java.lang.Override public boolean hasPrefrdMtd() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
     * @return The enum numeric value on the wire for prefrdMtd.
     */
    @java.lang.Override public int getPrefrdMtdValue() {
      return prefrdMtd_;
    }
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
     * @return The prefrdMtd.
     */
    @java.lang.Override public com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code getPrefrdMtd() {
      com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code result = com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code.forNumber(prefrdMtd_);
      return result == null ? com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nmPrfx_ != com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code.DOCT.getNumber()) {
        output.writeEnum(1, nmPrfx_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nm_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nm_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phneNb_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phneNb_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobNb_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mobNb_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(faxNb_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, faxNb_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(emailAdr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, emailAdr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(emailPurp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, emailPurp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jobTitl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, jobTitl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rspnsblty_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, rspnsblty_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dept_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, dept_);
      }
      for (int i = 0; i < othr_.size(); i++) {
        output.writeMessage(11, othr_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(12, prefrdMtd_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nmPrfx_ != com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code.DOCT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, nmPrfx_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nm_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nm_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phneNb_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phneNb_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobNb_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mobNb_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(faxNb_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, faxNb_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(emailAdr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, emailAdr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(emailPurp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, emailPurp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jobTitl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, jobTitl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rspnsblty_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, rspnsblty_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dept_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, dept_);
      }
      for (int i = 0; i < othr_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, othr_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(12, prefrdMtd_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4)) {
        return super.equals(obj);
      }
      com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 other = (com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4) obj;

      if (nmPrfx_ != other.nmPrfx_) return false;
      if (!getNm()
          .equals(other.getNm())) return false;
      if (!getPhneNb()
          .equals(other.getPhneNb())) return false;
      if (!getMobNb()
          .equals(other.getMobNb())) return false;
      if (!getFaxNb()
          .equals(other.getFaxNb())) return false;
      if (!getEmailAdr()
          .equals(other.getEmailAdr())) return false;
      if (!getEmailPurp()
          .equals(other.getEmailPurp())) return false;
      if (!getJobTitl()
          .equals(other.getJobTitl())) return false;
      if (!getRspnsblty()
          .equals(other.getRspnsblty())) return false;
      if (!getDept()
          .equals(other.getDept())) return false;
      if (!getOthrList()
          .equals(other.getOthrList())) return false;
      if (hasPrefrdMtd() != other.hasPrefrdMtd()) return false;
      if (hasPrefrdMtd()) {
        if (prefrdMtd_ != other.prefrdMtd_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NMPRFX_FIELD_NUMBER;
      hash = (53 * hash) + nmPrfx_;
      hash = (37 * hash) + NM_FIELD_NUMBER;
      hash = (53 * hash) + getNm().hashCode();
      hash = (37 * hash) + PHNENB_FIELD_NUMBER;
      hash = (53 * hash) + getPhneNb().hashCode();
      hash = (37 * hash) + MOBNB_FIELD_NUMBER;
      hash = (53 * hash) + getMobNb().hashCode();
      hash = (37 * hash) + FAXNB_FIELD_NUMBER;
      hash = (53 * hash) + getFaxNb().hashCode();
      hash = (37 * hash) + EMAILADR_FIELD_NUMBER;
      hash = (53 * hash) + getEmailAdr().hashCode();
      hash = (37 * hash) + EMAILPURP_FIELD_NUMBER;
      hash = (53 * hash) + getEmailPurp().hashCode();
      hash = (37 * hash) + JOBTITL_FIELD_NUMBER;
      hash = (53 * hash) + getJobTitl().hashCode();
      hash = (37 * hash) + RSPNSBLTY_FIELD_NUMBER;
      hash = (53 * hash) + getRspnsblty().hashCode();
      hash = (37 * hash) + DEPT_FIELD_NUMBER;
      hash = (53 * hash) + getDept().hashCode();
      if (getOthrCount() > 0) {
        hash = (37 * hash) + OTHR_FIELD_NUMBER;
        hash = (53 * hash) + getOthrList().hashCode();
      }
      if (hasPrefrdMtd()) {
        hash = (37 * hash) + PREFRDMTD_FIELD_NUMBER;
        hash = (53 * hash) + prefrdMtd_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bank.core.proto.pain_008_001_10.Contact4}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bank.core.proto.pain_008_001_10.Contact4)
        com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bank.core.proto.pain_008_001_10.Contact4OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_Contact4_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bank.core.proto.pain_008_001_10.Contact4OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_Contact4_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.class, com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.Builder.class);
      }

      // Construct using com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nmPrfx_ = 0;
        nm_ = "";
        phneNb_ = "";
        mobNb_ = "";
        faxNb_ = "";
        emailAdr_ = "";
        emailPurp_ = "";
        jobTitl_ = "";
        rspnsblty_ = "";
        dept_ = "";
        if (othrBuilder_ == null) {
          othr_ = java.util.Collections.emptyList();
        } else {
          othr_ = null;
          othrBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        prefrdMtd_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bank.core.proto.pain_008_001_10.Contact4OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_Contact4_descriptor;
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 getDefaultInstanceForType() {
        return com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.getDefaultInstance();
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 build() {
        com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 buildPartial() {
        com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 result = new com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 result) {
        if (othrBuilder_ == null) {
          if (((bitField0_ & 0x00000400) != 0)) {
            othr_ = java.util.Collections.unmodifiableList(othr_);
            bitField0_ = (bitField0_ & ~0x00000400);
          }
          result.othr_ = othr_;
        } else {
          result.othr_ = othrBuilder_.build();
        }
      }

      private void buildPartial0(com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nmPrfx_ = nmPrfx_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nm_ = nm_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.phneNb_ = phneNb_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.mobNb_ = mobNb_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.faxNb_ = faxNb_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.emailAdr_ = emailAdr_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.emailPurp_ = emailPurp_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.jobTitl_ = jobTitl_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.rspnsblty_ = rspnsblty_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.dept_ = dept_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.prefrdMtd_ = prefrdMtd_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4) {
          return mergeFrom((com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 other) {
        if (other == com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.getDefaultInstance()) return this;
        if (other.nmPrfx_ != 0) {
          setNmPrfxValue(other.getNmPrfxValue());
        }
        if (!other.getNm().isEmpty()) {
          nm_ = other.nm_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPhneNb().isEmpty()) {
          phneNb_ = other.phneNb_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getMobNb().isEmpty()) {
          mobNb_ = other.mobNb_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getFaxNb().isEmpty()) {
          faxNb_ = other.faxNb_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getEmailAdr().isEmpty()) {
          emailAdr_ = other.emailAdr_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getEmailPurp().isEmpty()) {
          emailPurp_ = other.emailPurp_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getJobTitl().isEmpty()) {
          jobTitl_ = other.jobTitl_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getRspnsblty().isEmpty()) {
          rspnsblty_ = other.rspnsblty_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (!other.getDept().isEmpty()) {
          dept_ = other.dept_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (othrBuilder_ == null) {
          if (!other.othr_.isEmpty()) {
            if (othr_.isEmpty()) {
              othr_ = other.othr_;
              bitField0_ = (bitField0_ & ~0x00000400);
            } else {
              ensureOthrIsMutable();
              othr_.addAll(other.othr_);
            }
            onChanged();
          }
        } else {
          if (!other.othr_.isEmpty()) {
            if (othrBuilder_.isEmpty()) {
              othrBuilder_.dispose();
              othrBuilder_ = null;
              othr_ = other.othr_;
              bitField0_ = (bitField0_ & ~0x00000400);
              othrBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOthrFieldBuilder() : null;
            } else {
              othrBuilder_.addAllMessages(other.othr_);
            }
          }
        }
        if (other.hasPrefrdMtd()) {
          setPrefrdMtd(other.getPrefrdMtd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                nmPrfx_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                nm_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                phneNb_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                mobNb_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                faxNb_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                emailAdr_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                emailPurp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                jobTitl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                rspnsblty_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                dept_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1 m =
                    input.readMessage(
                        com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.parser(),
                        extensionRegistry);
                if (othrBuilder_ == null) {
                  ensureOthrIsMutable();
                  othr_.add(m);
                } else {
                  othrBuilder_.addMessage(m);
                }
                break;
              } // case 90
              case 96: {
                prefrdMtd_ = input.readEnum();
                bitField0_ |= 0x00000800;
                break;
              } // case 96
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int nmPrfx_ = 0;
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.NamePrefix2Code NmPrfx = 1;</code>
       * @return The enum numeric value on the wire for nmPrfx.
       */
      @java.lang.Override public int getNmPrfxValue() {
        return nmPrfx_;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.NamePrefix2Code NmPrfx = 1;</code>
       * @param value The enum numeric value on the wire for nmPrfx to set.
       * @return This builder for chaining.
       */
      public Builder setNmPrfxValue(int value) {
        nmPrfx_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.NamePrefix2Code NmPrfx = 1;</code>
       * @return The nmPrfx.
       */
      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code getNmPrfx() {
        com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code result = com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code.forNumber(nmPrfx_);
        return result == null ? com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.NamePrefix2Code NmPrfx = 1;</code>
       * @param value The nmPrfx to set.
       * @return This builder for chaining.
       */
      public Builder setNmPrfx(com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.NamePrefix2Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        nmPrfx_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.bank.core.proto.pain_008_001_10.NamePrefix2Code NmPrfx = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNmPrfx() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nmPrfx_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nm_ = "";
      /**
       * <code>string Nm = 2;</code>
       * @return The nm.
       */
      public java.lang.String getNm() {
        java.lang.Object ref = nm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nm_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Nm = 2;</code>
       * @return The bytes for nm.
       */
      public com.google.protobuf.ByteString
          getNmBytes() {
        java.lang.Object ref = nm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Nm = 2;</code>
       * @param value The nm to set.
       * @return This builder for chaining.
       */
      public Builder setNm(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nm_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string Nm = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNm() {
        nm_ = getDefaultInstance().getNm();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string Nm = 2;</code>
       * @param value The bytes for nm to set.
       * @return This builder for chaining.
       */
      public Builder setNmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nm_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object phneNb_ = "";
      /**
       * <code>string PhneNb = 3;</code>
       * @return The phneNb.
       */
      public java.lang.String getPhneNb() {
        java.lang.Object ref = phneNb_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phneNb_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string PhneNb = 3;</code>
       * @return The bytes for phneNb.
       */
      public com.google.protobuf.ByteString
          getPhneNbBytes() {
        java.lang.Object ref = phneNb_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phneNb_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string PhneNb = 3;</code>
       * @param value The phneNb to set.
       * @return This builder for chaining.
       */
      public Builder setPhneNb(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        phneNb_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string PhneNb = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhneNb() {
        phneNb_ = getDefaultInstance().getPhneNb();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string PhneNb = 3;</code>
       * @param value The bytes for phneNb to set.
       * @return This builder for chaining.
       */
      public Builder setPhneNbBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        phneNb_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object mobNb_ = "";
      /**
       * <code>string MobNb = 4;</code>
       * @return The mobNb.
       */
      public java.lang.String getMobNb() {
        java.lang.Object ref = mobNb_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobNb_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string MobNb = 4;</code>
       * @return The bytes for mobNb.
       */
      public com.google.protobuf.ByteString
          getMobNbBytes() {
        java.lang.Object ref = mobNb_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobNb_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MobNb = 4;</code>
       * @param value The mobNb to set.
       * @return This builder for chaining.
       */
      public Builder setMobNb(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mobNb_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string MobNb = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobNb() {
        mobNb_ = getDefaultInstance().getMobNb();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string MobNb = 4;</code>
       * @param value The bytes for mobNb to set.
       * @return This builder for chaining.
       */
      public Builder setMobNbBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mobNb_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object faxNb_ = "";
      /**
       * <code>string FaxNb = 5;</code>
       * @return The faxNb.
       */
      public java.lang.String getFaxNb() {
        java.lang.Object ref = faxNb_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          faxNb_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FaxNb = 5;</code>
       * @return The bytes for faxNb.
       */
      public com.google.protobuf.ByteString
          getFaxNbBytes() {
        java.lang.Object ref = faxNb_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          faxNb_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FaxNb = 5;</code>
       * @param value The faxNb to set.
       * @return This builder for chaining.
       */
      public Builder setFaxNb(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        faxNb_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string FaxNb = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFaxNb() {
        faxNb_ = getDefaultInstance().getFaxNb();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string FaxNb = 5;</code>
       * @param value The bytes for faxNb to set.
       * @return This builder for chaining.
       */
      public Builder setFaxNbBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        faxNb_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object emailAdr_ = "";
      /**
       * <code>string EmailAdr = 6;</code>
       * @return The emailAdr.
       */
      public java.lang.String getEmailAdr() {
        java.lang.Object ref = emailAdr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emailAdr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string EmailAdr = 6;</code>
       * @return The bytes for emailAdr.
       */
      public com.google.protobuf.ByteString
          getEmailAdrBytes() {
        java.lang.Object ref = emailAdr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emailAdr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string EmailAdr = 6;</code>
       * @param value The emailAdr to set.
       * @return This builder for chaining.
       */
      public Builder setEmailAdr(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        emailAdr_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string EmailAdr = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmailAdr() {
        emailAdr_ = getDefaultInstance().getEmailAdr();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string EmailAdr = 6;</code>
       * @param value The bytes for emailAdr to set.
       * @return This builder for chaining.
       */
      public Builder setEmailAdrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        emailAdr_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object emailPurp_ = "";
      /**
       * <code>string EmailPurp = 7;</code>
       * @return The emailPurp.
       */
      public java.lang.String getEmailPurp() {
        java.lang.Object ref = emailPurp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emailPurp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string EmailPurp = 7;</code>
       * @return The bytes for emailPurp.
       */
      public com.google.protobuf.ByteString
          getEmailPurpBytes() {
        java.lang.Object ref = emailPurp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emailPurp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string EmailPurp = 7;</code>
       * @param value The emailPurp to set.
       * @return This builder for chaining.
       */
      public Builder setEmailPurp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        emailPurp_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string EmailPurp = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmailPurp() {
        emailPurp_ = getDefaultInstance().getEmailPurp();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string EmailPurp = 7;</code>
       * @param value The bytes for emailPurp to set.
       * @return This builder for chaining.
       */
      public Builder setEmailPurpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        emailPurp_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object jobTitl_ = "";
      /**
       * <code>string JobTitl = 8;</code>
       * @return The jobTitl.
       */
      public java.lang.String getJobTitl() {
        java.lang.Object ref = jobTitl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobTitl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string JobTitl = 8;</code>
       * @return The bytes for jobTitl.
       */
      public com.google.protobuf.ByteString
          getJobTitlBytes() {
        java.lang.Object ref = jobTitl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobTitl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string JobTitl = 8;</code>
       * @param value The jobTitl to set.
       * @return This builder for chaining.
       */
      public Builder setJobTitl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        jobTitl_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string JobTitl = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobTitl() {
        jobTitl_ = getDefaultInstance().getJobTitl();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string JobTitl = 8;</code>
       * @param value The bytes for jobTitl to set.
       * @return This builder for chaining.
       */
      public Builder setJobTitlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        jobTitl_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object rspnsblty_ = "";
      /**
       * <code>string Rspnsblty = 9;</code>
       * @return The rspnsblty.
       */
      public java.lang.String getRspnsblty() {
        java.lang.Object ref = rspnsblty_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rspnsblty_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Rspnsblty = 9;</code>
       * @return The bytes for rspnsblty.
       */
      public com.google.protobuf.ByteString
          getRspnsbltyBytes() {
        java.lang.Object ref = rspnsblty_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rspnsblty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Rspnsblty = 9;</code>
       * @param value The rspnsblty to set.
       * @return This builder for chaining.
       */
      public Builder setRspnsblty(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rspnsblty_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string Rspnsblty = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRspnsblty() {
        rspnsblty_ = getDefaultInstance().getRspnsblty();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string Rspnsblty = 9;</code>
       * @param value The bytes for rspnsblty to set.
       * @return This builder for chaining.
       */
      public Builder setRspnsbltyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rspnsblty_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private java.lang.Object dept_ = "";
      /**
       * <code>string Dept = 10;</code>
       * @return The dept.
       */
      public java.lang.String getDept() {
        java.lang.Object ref = dept_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dept_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Dept = 10;</code>
       * @return The bytes for dept.
       */
      public com.google.protobuf.ByteString
          getDeptBytes() {
        java.lang.Object ref = dept_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dept_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Dept = 10;</code>
       * @param value The dept to set.
       * @return This builder for chaining.
       */
      public Builder setDept(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dept_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string Dept = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearDept() {
        dept_ = getDefaultInstance().getDept();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string Dept = 10;</code>
       * @param value The bytes for dept to set.
       * @return This builder for chaining.
       */
      public Builder setDeptBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dept_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private java.util.List<com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1> othr_ =
        java.util.Collections.emptyList();
      private void ensureOthrIsMutable() {
        if (!((bitField0_ & 0x00000400) != 0)) {
          othr_ = new java.util.ArrayList<com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1>(othr_);
          bitField0_ |= 0x00000400;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1OrBuilder> othrBuilder_;

      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public java.util.List<com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1> getOthrList() {
        if (othrBuilder_ == null) {
          return java.util.Collections.unmodifiableList(othr_);
        } else {
          return othrBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public int getOthrCount() {
        if (othrBuilder_ == null) {
          return othr_.size();
        } else {
          return othrBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1 getOthr(int index) {
        if (othrBuilder_ == null) {
          return othr_.get(index);
        } else {
          return othrBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public Builder setOthr(
          int index, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1 value) {
        if (othrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOthrIsMutable();
          othr_.set(index, value);
          onChanged();
        } else {
          othrBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public Builder setOthr(
          int index, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder builderForValue) {
        if (othrBuilder_ == null) {
          ensureOthrIsMutable();
          othr_.set(index, builderForValue.build());
          onChanged();
        } else {
          othrBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public Builder addOthr(com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1 value) {
        if (othrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOthrIsMutable();
          othr_.add(value);
          onChanged();
        } else {
          othrBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public Builder addOthr(
          int index, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1 value) {
        if (othrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOthrIsMutable();
          othr_.add(index, value);
          onChanged();
        } else {
          othrBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public Builder addOthr(
          com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder builderForValue) {
        if (othrBuilder_ == null) {
          ensureOthrIsMutable();
          othr_.add(builderForValue.build());
          onChanged();
        } else {
          othrBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public Builder addOthr(
          int index, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder builderForValue) {
        if (othrBuilder_ == null) {
          ensureOthrIsMutable();
          othr_.add(index, builderForValue.build());
          onChanged();
        } else {
          othrBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public Builder addAllOthr(
          java.lang.Iterable<? extends com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1> values) {
        if (othrBuilder_ == null) {
          ensureOthrIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, othr_);
          onChanged();
        } else {
          othrBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public Builder clearOthr() {
        if (othrBuilder_ == null) {
          othr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000400);
          onChanged();
        } else {
          othrBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public Builder removeOthr(int index) {
        if (othrBuilder_ == null) {
          ensureOthrIsMutable();
          othr_.remove(index);
          onChanged();
        } else {
          othrBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder getOthrBuilder(
          int index) {
        return getOthrFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1OrBuilder getOthrOrBuilder(
          int index) {
        if (othrBuilder_ == null) {
          return othr_.get(index);  } else {
          return othrBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public java.util.List<? extends com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1OrBuilder> 
           getOthrOrBuilderList() {
        if (othrBuilder_ != null) {
          return othrBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(othr_);
        }
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder addOthrBuilder() {
        return getOthrFieldBuilder().addBuilder(
            com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.getDefaultInstance());
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder addOthrBuilder(
          int index) {
        return getOthrFieldBuilder().addBuilder(
            index, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.getDefaultInstance());
      }
      /**
       * <code>repeated .com.bank.core.proto.pain_008_001_10.OtherContact1 Othr = 11;</code>
       */
      public java.util.List<com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder> 
           getOthrBuilderList() {
        return getOthrFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1OrBuilder> 
          getOthrFieldBuilder() {
        if (othrBuilder_ == null) {
          othrBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1.Builder, com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.OtherContact1OrBuilder>(
                  othr_,
                  ((bitField0_ & 0x00000400) != 0),
                  getParentForChildren(),
                  isClean());
          othr_ = null;
        }
        return othrBuilder_;
      }

      private int prefrdMtd_ = 0;
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
       * @return Whether the prefrdMtd field is set.
       */
      @java.lang.Override public boolean hasPrefrdMtd() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
       * @return The enum numeric value on the wire for prefrdMtd.
       */
      @java.lang.Override public int getPrefrdMtdValue() {
        return prefrdMtd_;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
       * @param value The enum numeric value on the wire for prefrdMtd to set.
       * @return This builder for chaining.
       */
      public Builder setPrefrdMtdValue(int value) {
        prefrdMtd_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
       * @return The prefrdMtd.
       */
      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code getPrefrdMtd() {
        com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code result = com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code.forNumber(prefrdMtd_);
        return result == null ? com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
       * @param value The prefrdMtd to set.
       * @return This builder for chaining.
       */
      public Builder setPrefrdMtd(com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.PreferredContactMethod1Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000800;
        prefrdMtd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PreferredContactMethod1Code PrefrdMtd = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrefrdMtd() {
        bitField0_ = (bitField0_ & ~0x00000800);
        prefrdMtd_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bank.core.proto.pain_008_001_10.Contact4)
    }

    // @@protoc_insertion_point(class_scope:com.bank.core.proto.pain_008_001_10.Contact4)
    private static final com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4();
    }

    public static com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Contact4>
        PARSER = new com.google.protobuf.AbstractParser<Contact4>() {
      @java.lang.Override
      public Contact4 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Contact4> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contact4> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bank_core_proto_pain_008_001_10_Contact4_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bank_core_proto_pain_008_001_10_Contact4_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/Contact4.proto\022#com.bank.core.pr" +
      "oto.pain_008_001_10\032\033proto/NamePrefix2Co" +
      "de.proto\032\031proto/OtherContact1.proto\032\'pro" +
      "to/PreferredContactMethod1Code.proto\"\213\003\n" +
      "\010Contact4\022D\n\006NmPrfx\030\001 \001(\01624.com.bank.cor" +
      "e.proto.pain_008_001_10.NamePrefix2Code\022" +
      "\n\n\002Nm\030\002 \001(\t\022\016\n\006PhneNb\030\003 \001(\t\022\r\n\005MobNb\030\004 \001" +
      "(\t\022\r\n\005FaxNb\030\005 \001(\t\022\020\n\010EmailAdr\030\006 \001(\t\022\021\n\tE" +
      "mailPurp\030\007 \001(\t\022\017\n\007JobTitl\030\010 \001(\t\022\021\n\tRspns" +
      "blty\030\t \001(\t\022\014\n\004Dept\030\n \001(\t\022@\n\004Othr\030\013 \003(\01322" +
      ".com.bank.core.proto.pain_008_001_10.Oth" +
      "erContact1\022X\n\tPrefrdMtd\030\014 \001(\0162@.com.bank" +
      ".core.proto.pain_008_001_10.PreferredCon" +
      "tactMethod1CodeH\000\210\001\001B\014\n\n_PrefrdMtdb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.getDescriptor(),
          com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.getDescriptor(),
          com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.getDescriptor(),
        });
    internal_static_com_bank_core_proto_pain_008_001_10_Contact4_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bank_core_proto_pain_008_001_10_Contact4_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bank_core_proto_pain_008_001_10_Contact4_descriptor,
        new java.lang.String[] { "NmPrfx", "Nm", "PhneNb", "MobNb", "FaxNb", "EmailAdr", "EmailPurp", "JobTitl", "Rspnsblty", "Dept", "Othr", "PrefrdMtd", });
    com.bank.core.proto.pain_008_001_10.NamePrefix2CodeOuterClass.getDescriptor();
    com.bank.core.proto.pain_008_001_10.OtherContact1OuterClass.getDescriptor();
    com.bank.core.proto.pain_008_001_10.PreferredContactMethod1CodeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
