// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/PartyIdentification135.proto

// Protobuf Java Version: 3.25.3
package com.bank.core.proto.pain_008_001_10;

public final class PartyIdentification135OuterClass {
  private PartyIdentification135OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PartyIdentification135OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bank.core.proto.pain_008_001_10.PartyIdentification135)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Nm = 1;</code>
     * @return The nm.
     */
    java.lang.String getNm();
    /**
     * <code>string Nm = 1;</code>
     * @return The bytes for nm.
     */
    com.google.protobuf.ByteString
        getNmBytes();

    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
     * @return Whether the pstlAdr field is set.
     */
    boolean hasPstlAdr();
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
     * @return The pstlAdr.
     */
    com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24 getPstlAdr();
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
     */
    com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24OrBuilder getPstlAdrOrBuilder();

    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
     * @return The id.
     */
    com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice getId();
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
     */
    com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38ChoiceOrBuilder getIdOrBuilder();

    /**
     * <code>optional string CtryOfRes = 4;</code>
     * @return Whether the ctryOfRes field is set.
     */
    boolean hasCtryOfRes();
    /**
     * <code>optional string CtryOfRes = 4;</code>
     * @return The ctryOfRes.
     */
    java.lang.String getCtryOfRes();
    /**
     * <code>optional string CtryOfRes = 4;</code>
     * @return The bytes for ctryOfRes.
     */
    com.google.protobuf.ByteString
        getCtryOfResBytes();

    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
     * @return Whether the ctctDtls field is set.
     */
    boolean hasCtctDtls();
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
     * @return The ctctDtls.
     */
    com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 getCtctDtls();
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
     */
    com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4OrBuilder getCtctDtlsOrBuilder();
  }
  /**
   * Protobuf type {@code com.bank.core.proto.pain_008_001_10.PartyIdentification135}
   */
  public static final class PartyIdentification135 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bank.core.proto.pain_008_001_10.PartyIdentification135)
      PartyIdentification135OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PartyIdentification135.newBuilder() to construct.
    private PartyIdentification135(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PartyIdentification135() {
      nm_ = "";
      ctryOfRes_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PartyIdentification135();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135.class, com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135.Builder.class);
    }

    private int bitField0_;
    public static final int NM_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nm_ = "";
    /**
     * <code>string Nm = 1;</code>
     * @return The nm.
     */
    @java.lang.Override
    public java.lang.String getNm() {
      java.lang.Object ref = nm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nm_ = s;
        return s;
      }
    }
    /**
     * <code>string Nm = 1;</code>
     * @return The bytes for nm.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNmBytes() {
      java.lang.Object ref = nm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PSTLADR_FIELD_NUMBER = 2;
    private com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24 pstlAdr_;
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
     * @return Whether the pstlAdr field is set.
     */
    @java.lang.Override
    public boolean hasPstlAdr() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
     * @return The pstlAdr.
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24 getPstlAdr() {
      return pstlAdr_ == null ? com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.getDefaultInstance() : pstlAdr_;
    }
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24OrBuilder getPstlAdrOrBuilder() {
      return pstlAdr_ == null ? com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.getDefaultInstance() : pstlAdr_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice id_;
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice getId() {
      return id_ == null ? com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.getDefaultInstance() : id_;
    }
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38ChoiceOrBuilder getIdOrBuilder() {
      return id_ == null ? com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.getDefaultInstance() : id_;
    }

    public static final int CTRYOFRES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ctryOfRes_ = "";
    /**
     * <code>optional string CtryOfRes = 4;</code>
     * @return Whether the ctryOfRes field is set.
     */
    @java.lang.Override
    public boolean hasCtryOfRes() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string CtryOfRes = 4;</code>
     * @return The ctryOfRes.
     */
    @java.lang.Override
    public java.lang.String getCtryOfRes() {
      java.lang.Object ref = ctryOfRes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ctryOfRes_ = s;
        return s;
      }
    }
    /**
     * <code>optional string CtryOfRes = 4;</code>
     * @return The bytes for ctryOfRes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCtryOfResBytes() {
      java.lang.Object ref = ctryOfRes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ctryOfRes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CTCTDTLS_FIELD_NUMBER = 5;
    private com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 ctctDtls_;
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
     * @return Whether the ctctDtls field is set.
     */
    @java.lang.Override
    public boolean hasCtctDtls() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
     * @return The ctctDtls.
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 getCtctDtls() {
      return ctctDtls_ == null ? com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.getDefaultInstance() : ctctDtls_;
    }
    /**
     * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
     */
    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4OrBuilder getCtctDtlsOrBuilder() {
      return ctctDtls_ == null ? com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.getDefaultInstance() : ctctDtls_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nm_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nm_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getPstlAdr());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getId());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ctryOfRes_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(5, getCtctDtls());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nm_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nm_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPstlAdr());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getId());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ctryOfRes_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCtctDtls());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135)) {
        return super.equals(obj);
      }
      com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 other = (com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135) obj;

      if (!getNm()
          .equals(other.getNm())) return false;
      if (hasPstlAdr() != other.hasPstlAdr()) return false;
      if (hasPstlAdr()) {
        if (!getPstlAdr()
            .equals(other.getPstlAdr())) return false;
      }
      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasCtryOfRes() != other.hasCtryOfRes()) return false;
      if (hasCtryOfRes()) {
        if (!getCtryOfRes()
            .equals(other.getCtryOfRes())) return false;
      }
      if (hasCtctDtls() != other.hasCtctDtls()) return false;
      if (hasCtctDtls()) {
        if (!getCtctDtls()
            .equals(other.getCtctDtls())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NM_FIELD_NUMBER;
      hash = (53 * hash) + getNm().hashCode();
      if (hasPstlAdr()) {
        hash = (37 * hash) + PSTLADR_FIELD_NUMBER;
        hash = (53 * hash) + getPstlAdr().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasCtryOfRes()) {
        hash = (37 * hash) + CTRYOFRES_FIELD_NUMBER;
        hash = (53 * hash) + getCtryOfRes().hashCode();
      }
      if (hasCtctDtls()) {
        hash = (37 * hash) + CTCTDTLS_FIELD_NUMBER;
        hash = (53 * hash) + getCtctDtls().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bank.core.proto.pain_008_001_10.PartyIdentification135}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bank.core.proto.pain_008_001_10.PartyIdentification135)
        com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135.class, com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135.Builder.class);
      }

      // Construct using com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPstlAdrFieldBuilder();
          getIdFieldBuilder();
          getCtctDtlsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nm_ = "";
        pstlAdr_ = null;
        if (pstlAdrBuilder_ != null) {
          pstlAdrBuilder_.dispose();
          pstlAdrBuilder_ = null;
        }
        id_ = null;
        if (idBuilder_ != null) {
          idBuilder_.dispose();
          idBuilder_ = null;
        }
        ctryOfRes_ = "";
        ctctDtls_ = null;
        if (ctctDtlsBuilder_ != null) {
          ctctDtlsBuilder_.dispose();
          ctctDtlsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_descriptor;
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 getDefaultInstanceForType() {
        return com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135.getDefaultInstance();
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 build() {
        com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 buildPartial() {
        com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 result = new com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nm_ = nm_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pstlAdr_ = pstlAdrBuilder_ == null
              ? pstlAdr_
              : pstlAdrBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.id_ = idBuilder_ == null
              ? id_
              : idBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ctryOfRes_ = ctryOfRes_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.ctctDtls_ = ctctDtlsBuilder_ == null
              ? ctctDtls_
              : ctctDtlsBuilder_.build();
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135) {
          return mergeFrom((com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 other) {
        if (other == com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135.getDefaultInstance()) return this;
        if (!other.getNm().isEmpty()) {
          nm_ = other.nm_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasPstlAdr()) {
          mergePstlAdr(other.getPstlAdr());
        }
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.hasCtryOfRes()) {
          ctryOfRes_ = other.ctryOfRes_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasCtctDtls()) {
          mergeCtctDtls(other.getCtctDtls());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nm_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getPstlAdrFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getIdFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                ctryOfRes_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getCtctDtlsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nm_ = "";
      /**
       * <code>string Nm = 1;</code>
       * @return The nm.
       */
      public java.lang.String getNm() {
        java.lang.Object ref = nm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nm_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Nm = 1;</code>
       * @return The bytes for nm.
       */
      public com.google.protobuf.ByteString
          getNmBytes() {
        java.lang.Object ref = nm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Nm = 1;</code>
       * @param value The nm to set.
       * @return This builder for chaining.
       */
      public Builder setNm(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nm_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string Nm = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNm() {
        nm_ = getDefaultInstance().getNm();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string Nm = 1;</code>
       * @param value The bytes for nm to set.
       * @return This builder for chaining.
       */
      public Builder setNmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nm_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24 pstlAdr_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24, com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.Builder, com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24OrBuilder> pstlAdrBuilder_;
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
       * @return Whether the pstlAdr field is set.
       */
      public boolean hasPstlAdr() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
       * @return The pstlAdr.
       */
      public com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24 getPstlAdr() {
        if (pstlAdrBuilder_ == null) {
          return pstlAdr_ == null ? com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.getDefaultInstance() : pstlAdr_;
        } else {
          return pstlAdrBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
       */
      public Builder setPstlAdr(com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24 value) {
        if (pstlAdrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pstlAdr_ = value;
        } else {
          pstlAdrBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
       */
      public Builder setPstlAdr(
          com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.Builder builderForValue) {
        if (pstlAdrBuilder_ == null) {
          pstlAdr_ = builderForValue.build();
        } else {
          pstlAdrBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
       */
      public Builder mergePstlAdr(com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24 value) {
        if (pstlAdrBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            pstlAdr_ != null &&
            pstlAdr_ != com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.getDefaultInstance()) {
            getPstlAdrBuilder().mergeFrom(value);
          } else {
            pstlAdr_ = value;
          }
        } else {
          pstlAdrBuilder_.mergeFrom(value);
        }
        if (pstlAdr_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
       */
      public Builder clearPstlAdr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pstlAdr_ = null;
        if (pstlAdrBuilder_ != null) {
          pstlAdrBuilder_.dispose();
          pstlAdrBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
       */
      public com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.Builder getPstlAdrBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPstlAdrFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
       */
      public com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24OrBuilder getPstlAdrOrBuilder() {
        if (pstlAdrBuilder_ != null) {
          return pstlAdrBuilder_.getMessageOrBuilder();
        } else {
          return pstlAdr_ == null ?
              com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.getDefaultInstance() : pstlAdr_;
        }
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.PostalAddress24 PstlAdr = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24, com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.Builder, com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24OrBuilder> 
          getPstlAdrFieldBuilder() {
        if (pstlAdrBuilder_ == null) {
          pstlAdrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24, com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24.Builder, com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.PostalAddress24OrBuilder>(
                  getPstlAdr(),
                  getParentForChildren(),
                  isClean());
          pstlAdr_ = null;
        }
        return pstlAdrBuilder_;
      }

      private com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice id_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice, com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.Builder, com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38ChoiceOrBuilder> idBuilder_;
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
       * @return The id.
       */
      public com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice getId() {
        if (idBuilder_ == null) {
          return id_ == null ? com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
       */
      public Builder setId(com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
       */
      public Builder setId(
          com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
       */
      public Builder mergeId(com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            id_ != null &&
            id_ != com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.getDefaultInstance()) {
            getIdBuilder().mergeFrom(value);
          } else {
            id_ = value;
          }
        } else {
          idBuilder_.mergeFrom(value);
        }
        if (id_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = null;
        if (idBuilder_ != null) {
          idBuilder_.dispose();
          idBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
       */
      public com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.Builder getIdBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
       */
      public com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38ChoiceOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Party38Choice Id = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice, com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.Builder, com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38ChoiceOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice, com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38Choice.Builder, com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.Party38ChoiceOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private java.lang.Object ctryOfRes_ = "";
      /**
       * <code>optional string CtryOfRes = 4;</code>
       * @return Whether the ctryOfRes field is set.
       */
      public boolean hasCtryOfRes() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string CtryOfRes = 4;</code>
       * @return The ctryOfRes.
       */
      public java.lang.String getCtryOfRes() {
        java.lang.Object ref = ctryOfRes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ctryOfRes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string CtryOfRes = 4;</code>
       * @return The bytes for ctryOfRes.
       */
      public com.google.protobuf.ByteString
          getCtryOfResBytes() {
        java.lang.Object ref = ctryOfRes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ctryOfRes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string CtryOfRes = 4;</code>
       * @param value The ctryOfRes to set.
       * @return This builder for chaining.
       */
      public Builder setCtryOfRes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ctryOfRes_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string CtryOfRes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCtryOfRes() {
        ctryOfRes_ = getDefaultInstance().getCtryOfRes();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string CtryOfRes = 4;</code>
       * @param value The bytes for ctryOfRes to set.
       * @return This builder for chaining.
       */
      public Builder setCtryOfResBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ctryOfRes_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 ctctDtls_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4, com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.Builder, com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4OrBuilder> ctctDtlsBuilder_;
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
       * @return Whether the ctctDtls field is set.
       */
      public boolean hasCtctDtls() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
       * @return The ctctDtls.
       */
      public com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 getCtctDtls() {
        if (ctctDtlsBuilder_ == null) {
          return ctctDtls_ == null ? com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.getDefaultInstance() : ctctDtls_;
        } else {
          return ctctDtlsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
       */
      public Builder setCtctDtls(com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 value) {
        if (ctctDtlsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ctctDtls_ = value;
        } else {
          ctctDtlsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
       */
      public Builder setCtctDtls(
          com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.Builder builderForValue) {
        if (ctctDtlsBuilder_ == null) {
          ctctDtls_ = builderForValue.build();
        } else {
          ctctDtlsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
       */
      public Builder mergeCtctDtls(com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4 value) {
        if (ctctDtlsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            ctctDtls_ != null &&
            ctctDtls_ != com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.getDefaultInstance()) {
            getCtctDtlsBuilder().mergeFrom(value);
          } else {
            ctctDtls_ = value;
          }
        } else {
          ctctDtlsBuilder_.mergeFrom(value);
        }
        if (ctctDtls_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
       */
      public Builder clearCtctDtls() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ctctDtls_ = null;
        if (ctctDtlsBuilder_ != null) {
          ctctDtlsBuilder_.dispose();
          ctctDtlsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
       */
      public com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.Builder getCtctDtlsBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getCtctDtlsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
       */
      public com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4OrBuilder getCtctDtlsOrBuilder() {
        if (ctctDtlsBuilder_ != null) {
          return ctctDtlsBuilder_.getMessageOrBuilder();
        } else {
          return ctctDtls_ == null ?
              com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.getDefaultInstance() : ctctDtls_;
        }
      }
      /**
       * <code>optional .com.bank.core.proto.pain_008_001_10.Contact4 CtctDtls = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4, com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.Builder, com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4OrBuilder> 
          getCtctDtlsFieldBuilder() {
        if (ctctDtlsBuilder_ == null) {
          ctctDtlsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4, com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4.Builder, com.bank.core.proto.pain_008_001_10.Contact4OuterClass.Contact4OrBuilder>(
                  getCtctDtls(),
                  getParentForChildren(),
                  isClean());
          ctctDtls_ = null;
        }
        return ctctDtlsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bank.core.proto.pain_008_001_10.PartyIdentification135)
    }

    // @@protoc_insertion_point(class_scope:com.bank.core.proto.pain_008_001_10.PartyIdentification135)
    private static final com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135();
    }

    public static com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PartyIdentification135>
        PARSER = new com.google.protobuf.AbstractParser<PartyIdentification135>() {
      @java.lang.Override
      public PartyIdentification135 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PartyIdentification135> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PartyIdentification135> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bank.core.proto.pain_008_001_10.PartyIdentification135OuterClass.PartyIdentification135 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"proto/PartyIdentification135.proto\022#co" +
      "m.bank.core.proto.pain_008_001_10\032\033proto" +
      "/PostalAddress24.proto\032\031proto/Party38Cho" +
      "ice.proto\032\024proto/Contact4.proto\"\301\002\n\026Part" +
      "yIdentification135\022\n\n\002Nm\030\001 \001(\t\022J\n\007PstlAd" +
      "r\030\002 \001(\01324.com.bank.core.proto.pain_008_0" +
      "01_10.PostalAddress24H\000\210\001\001\022C\n\002Id\030\003 \001(\01322" +
      ".com.bank.core.proto.pain_008_001_10.Par" +
      "ty38ChoiceH\001\210\001\001\022\026\n\tCtryOfRes\030\004 \001(\tH\002\210\001\001\022" +
      "D\n\010CtctDtls\030\005 \001(\0132-.com.bank.core.proto." +
      "pain_008_001_10.Contact4H\003\210\001\001B\n\n\010_PstlAd" +
      "rB\005\n\003_IdB\014\n\n_CtryOfResB\013\n\t_CtctDtlsb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.getDescriptor(),
          com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.getDescriptor(),
          com.bank.core.proto.pain_008_001_10.Contact4OuterClass.getDescriptor(),
        });
    internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bank_core_proto_pain_008_001_10_PartyIdentification135_descriptor,
        new java.lang.String[] { "Nm", "PstlAdr", "Id", "CtryOfRes", "CtctDtls", });
    com.bank.core.proto.pain_008_001_10.PostalAddress24OuterClass.getDescriptor();
    com.bank.core.proto.pain_008_001_10.Party38ChoiceOuterClass.getDescriptor();
    com.bank.core.proto.pain_008_001_10.Contact4OuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
